/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-fixed": "#3d1900",
        "surface-container-high": "#2b2b2b",
        "inverse-surface": "#e6e6e6",
        "secondary": "#f97316",
        "primary-fixed-dim": "#f97316",
        "tertiary-fixed": "#ffdbcc",
        "on-surface-variant": "#c4c7c5",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ffdbcc",
        "outline-variant": "#444746",
        "on-tertiary-fixed-variant": "#3d1900",
        "on-tertiary-container": "#3d1900",
        "on-background": "#e3e3e3",
        "primary": "#f97316",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#3d1900",
        "on-surface": "#e3e3e3",
        "background": "#131313",
        "surface-container": "#1d1d1d",
        "secondary-fixed": "#ffdbcc",
        "surface-container-highest": "#333333",
        "on-secondary-container": "#3d1900",
        "tertiary": "#f97316",
        "primary-container": "#8f3a00",
        "on-secondary-fixed-variant": "#3d1900",
        "inverse-primary": "#f97316",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-dim": "#131313",
        "surface": "#131313",
        "on-secondary-fixed": "#3d1900",
        "on-secondary": "#ffffff",
        "surface-variant": "#2b2b2b",
        "secondary-fixed-dim": "#f97316",
        "surface-container-low": "#1b1b1b",
        "on-primary-fixed-variant": "#3d1900",
        "error": "#ffb4ab",
        "inverse-on-surface": "#313033",
        "surface-tint": "#f97316",
        "secondary-container": "#8f3a00",
        "tertiary-container": "#8f3a00",
        "surface-bright": "#393939",
        "on-primary-container": "#ffdbcc",
        "tertiary-fixed-dim": "#f97316",
        "outline": "#8e918f",
        "brand-orange": "#f97316",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "8px",
        "sidebar-width": "260px",
        base: "4px",
        md: "16px",
        gutter: "24px",
        xs: "4px",
        "telemetry-panel-width": "340px",
        lg: "24px",
        xl: "32px",
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "label-caps": ["Inter"],
        "body-base": ["Inter"],
        "stat-lg": ["Inter"],
        "log-mono": ["JetBrains Mono"],
        "display-lg": ["Inter"],
        "body-bold": ["Inter"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
        "body-base": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        "stat-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "log-mono": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "display-lg": ["44px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-bold": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
